name: hello
on: [push]
jobs:
  test:
    runs-on: unduntu-latest
    steps:
      - name: Get Repository
        uses: actions/checkout@v3
      - name: Diello
        id: hello
        uses: AbdelhakBLD/helloworldaction@v2
        with:
          name: TOTO
        - name: Get output Diello
          run: echo "${{ steps.hello.outputs.response }}"