name: tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10, 12, 14, 16]
        app: [1.0.0, 2.0.0]
    steps:
      - name: Get repository
        uses: actions/checkout@v3
        with:
          ref: refs/tags/${{ matrix.app }}
      - name: Installer nodejs
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm i
      - name: Run tests
        run: npm run test
      - name: Run tests coverage
        run: npm run cover
      - name: download
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./reports
  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Get repository
        uses: actions/checkout@v3
      - name: Setup Docker qemu
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker buildX
        uses: docker/setup-buildx-action@v1
      - name: Login Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build & push Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/weather:latest
      - name: Hello world
        uses: AbdelhakBLD/helloworldaction@v2
        with:
          name: Toto